### ISSUE TITLE
Where are all the docs?

### ISSUE THREAD

**Issue by ceytalis** [d4software/QueryTree#11]
Looking in the Docs folder see a bunch of .md files, but when clicking on them seeing nothing.  Do see a change log that says docs moved from wiki to repo.  But where are they?

**Comment by dand4** [comment]
We're still working on them. The main README is pretty good now, and a few of them are done (customizing, docker and mail). But the rest still need to be written.

**Comment by dand4** [comment]
That's actually the next one we were going to write too. I think we can get this done next week some time. I'll keep you posted.

**Comment by PandelisZ** [comment]
Looks like dans gone ahead and written the atuojoin docs @ceytalis 

You can find them it here: https://github.com/d4software/QueryTree/blob/master/docs/autojoin.md
