### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by xylem69** [d4software/QueryTree#117]
Hi,

I am getting this error on build attempt (Win Server 2019, .NET SDK installed):
--

C:\QueryTree\Web>dotnet run
C:\QueryTree\Web\QueryTree.csproj : warning NU1701: Package 'dotless.AspNetHandler 1.6.7' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
C:\QueryTree\Web\QueryTree.csproj : warning NU1701: Package 'dotless.AspNetHandler 1.6.7' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
C:\Users\Administrator\.nuget\packages\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(131,5): error : rzc generate exited with code -2147450730. [C:\QueryTree\Web\QueryTree.csproj]

The build failed. Fix the build errors and run again.

**Comment by PandelisZ** [comment]
.... ' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework **'.NETCoreApp,Version=v2.2'.**  

`This package may not be fully compatible with your project.`

....
