### ISSUE TITLE
Unable to configure app for use behind Nginx reverse proxy

### ISSUE THREAD

**Issue by SysEngDan** [d4software/QueryTree#119]
I'm running QT with Docker, using image d4software/querytree:c63e66f. I have many, many website running behind the reverse proxy which work without issue. When configuring QT with a simple, basic proxy_pass config, the QT redirects to the Docker service name. It seems like out of the box, QT doesn't honor X-Forwarded-For and Proto headers.

Any advice?
```
        location / {
                resolver 127.0.0.11 valid=10s;
                real_ip_header proxy_protocol;
                set_real_ip_from 192.168.30.1/32;
                set $upstream reports_example_com_php;
                proxy_set_header X-Real-IP $proxy_protocol_addr;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_protocol_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass http://$upstream;
        }
```

**Comment by PandelisZ** [comment]
Thanks for the great feedback.

This is definately something that we should support as its pretty much the standard way of routing in the cloud native era.

**Comment by SysEngDan** [comment]
Should this be considered a big since proxy support is already written in readme.md?

“For use in production environments, QueryTree should be run behind a reverse proxy such as nginx. For more information on hosting QueryTree using nginx see: https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction”

**Comment by PandelisZ** [comment]
This project was originally refactored form a windows only .NET stack back in the day so theres definately lots of nice .NET core features we've missed.

Looks like it s amatter of enabling the forwarding headers. It's not something that's automatically taken care of:
```
using Microsoft.AspNetCore.HttpOverrides;

app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
});

app.UseAuthentication();
```

**Comment by PandelisZ** [comment]
@SysEngDan could you give `docker.io/d4software/querytree:reverse-proxy` a go?

**Comment by SysEngDan** [comment]
I gave it a shot  but I'm still saying the same response. What happens is that the application redirects from the initial request (https;//reports.example.com) to this https://reports_example_com_app/Account/Login?ReturnUrl=%2F (that's the docker service name). This tells me that the application isn't honoring X-Forwarded-Host (which contains the original hostname).
