### ISSUE TITLE
QueryTree does not email out scheduled report

### ISSUE THREAD

**Issue by larsrohrberg** [d4software/QueryTree#121]
I am able to configure the report to be emailed but it never shows up in my email.  I have checked my inbox, junk, and other email folders.  Nothing there.  What could cause emails from being sent from QueryTree?  Is there a server setting that needs to be turned on?  The client side UI experience indicates to the user that emailing out reports is possible.  The emails just don't show up.

**Comment by PandelisZ** [comment]
https://github.com/d4software/QueryTree/blob/master/docs/mail.md
