### ISSUE TITLE
Error during connectin to PostgreSQL: SSL is required

### ISSUE THREAD

**Issue by iyakhiev** [d4software/QueryTree#131]
Hi, 

My QueryTree is running with a valid LetsEncrypt certificate, but I still get an "SSL is required" error during a connection test. I'm trying to connect to a Managed Service for PostgreSQL by cloud.yandex.ru.

**Comment by iyakhiev** [comment]
I have port 6432, but when I go back to connection settings it always resets to 5432.

**Comment by PandelisZ** [comment]
https://cloud.yandex.com/en/docs/managed-postgresql/operations/connect#get-ssl-cert
