### ISSUE TITLE
New tables/Views added to database not showing

### ISSUE THREAD

**Issue by QuentinBennett** [d4software/QueryTree#135]
Duplicate of closed issue #109, but on a SQL Server database.

New Table/View shows when new connection created, but not showing on existing connection, created prior to the table/view.

Additionally, columns added/changed after the connection created are not reflected in the Query Tree, resulting in 'invalid column name' errors.

**Comment by harpsicord86** [comment]
Hi @QuentinBennett,

I had noticed this too and it turns out that QueryTree has a cache which updates every hour. If you reset your app pool in IIS, this usually gets any new view/tables to show. Have a try and see if this works for you.
