### ISSUE TITLE
Cannot install QueryTree from source

### ISSUE THREAD

**Issue by Jagrutiti** [d4software/QueryTree#136]
I installed the prerequisite and tried to install QueryTree from the source. 

But it still says: 
`You must install or update .NET to run this application.`

Do I need to install the .NET framework it is not mentioned in the documentation?
 
The output of `dotnet --version` command is 6.0.32

![image](https://user-images.githubusercontent.com/28809492/181179853-389b2e8c-db02-419b-894a-6d56fc239882.png)

**Comment by d4nt** [comment]
@Jagrutiti until recently, QueryTree required version 2.2 of dotnet, that was probably the issue. It has been updated to dotnet 6 now though,
