### ISSUE TITLE
Multi tenant situation 

### ISSUE THREAD

**Issue by KrunchMuffin** [d4software/QueryTree#145]
Curious if there is any way to do a multi-tenant setup? If not, would it be a matter of 1 docker per client? What would the requirements be for say 10 clients?

**Comment by d4nt** [comment]
The "Teams" feature could be used like that. Each user can invite others to join their team and share queries/reports within their team. The teams are isolated from each other and can't see each others data.

**Comment by KrunchMuffin** [comment]
oh, interesting. I will try it out . thanks
