### ISSUE TITLE
Unable to see values in drop downs on the filter section

### ISSUE THREAD

**Issue by tirsoh** [d4software/QueryTree#15]
I am able to connect to my postgres DB and see all the tables listed in the select your table section. When I select a table and click next in that section I see the following response in my devtools when hitting this URL: 
`http://localhost:8081/api/cache/a88ac14f06eb4512b7287a0501f2423a/0a1c9d5d-d9a7-4d02-8332-75cba76bb08f/?startRow=0&rowCount=10`

```
{"status":"error","errorText":"42703: column \"column_0\" does not exist","columns":[],"columnTypes":[],"rows":[],"rowCount":0,"query":null}
```

When I click on the filter section I see the drop downs but there are no values in those.
![screen shot 2018-05-10 at 8 51 46 am](https://user-images.githubusercontent.com/1945253/39873006-65e520b8-542f-11e8-8c06-c948e2de4701.png)

Any suggestions on what could be causing this?

**Comment by tirsoh** [comment]
CREATE TABLE IF NOT EXISTS myschema.tablename
(
  primary_id character(36) NOT NULL,
  profile_id character(36) NOT NULL,
  state_code text NOT NULL,
  class_code integer NOT NULL,
  license text NOT NULL,
  class text,
  record_created_on timestamp with time zone NOT NULL DEFAULT now(),
  status text,
  res_indicator boolean,
  issue_date date,
  effective_date date,
  expiration_date date,
  change_sequence bigint,
  source text,
  status_date date,
  digest_id character(32),
  CONSTRAINT tablename_pk PRIMARY KEY (primary_id)
  USING INDEX TABLESPACE indexspace,
  CONSTRAINT tablename_profile_id_fkey FOREIGN KEY (profile_id)
      REFERENCES myschema.profile (profile_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);

**Comment by dand4** [comment]
@tirsoh I've pushed a change (f0593ea) to the develop branch that I think might fix your issue. Could you checkout develop and retry? If this fixes your issue we can merge into master which will create a new release binary.

**Comment by tirsoh** [comment]
I am running this by using docker images because I am on a Mac and I don’t have any .net tools or experience so I won’t be able to build this on my machine. Could you provide me with a docker image to test with?

**Comment by tirsoh** [comment]
Ok let me give that a try and I will let you know.

**Comment by djshres** [comment]
I am able to connect to Sql Server and table are shown.
But when i click next nothing happens.
And can't filter datas.
![screenshot 162](https://user-images.githubusercontent.com/16093773/48978849-6605e800-f0da-11e8-95ec-fadb933a125f.png)
![screenshot 163](https://user-images.githubusercontent.com/16093773/48978850-6ef6b980-f0da-11e8-8fd0-7edba15166a0.png)
