### ISSUE TITLE
How to run in ubuntu?

### ISSUE THREAD

**Issue by Rhomennik** [d4software/QueryTree#17]
![image](https://user-images.githubusercontent.com/24496303/40661257-41aa6428-6321-11e8-9455-6018cccc825a.png)
![image](https://user-images.githubusercontent.com/24496303/40661310-63a65a8c-6321-11e8-8c15-3340a6e2a256.png)
![image](https://user-images.githubusercontent.com/24496303/40661342-79db05d2-6321-11e8-9ff6-b0589b43af73.png)
HELP ME .!!

**Comment by dand4** [comment]
Did you do the following?...

```
cd Web
dotnet run
```

**Comment by PandelisZ** [comment]
@Rhomennik Looks like you're running into apache trouble.

Try implementing the suggested configurations on here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.1&tabs=aspnetcore2x
