### ISSUE TITLE
No option to generate chart

### ISSUE THREAD

**Issue by s1monj** [d4software/QueryTree#20]
I connected to the database and successfully created a simple report of int x string

units_in_stock | company_name
4 | Tokyo Traders
5 | Lyngbysild
6 | Specialty Biscuits, Ltd.

From the README:
"Finally, you have the option of generating a chart from the data in the results panel."

I can not see this option anywhere on either the View Report or Edit Report screens and there are no errors in the log.

centos.7-x64
.NET Core SDKs installed:
  2.1.300 [/usr/share/dotnet/sdk]
.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Postgres 9.4

**Comment by dand4** [comment]
The Chart panel on the report builder is only shown if the data on the results panel has at least one numeric column. What is the data type of the units_in_stock column? Is it one of the data types listed in the IsNumericType function in tools.js:

```
tools.IsNumericType = function (theType) {
    switch (theType.toUpperCase()) {
        case "INTEGER":
        case "INT":
        case "SMALLINT":
        case "TINYINT":
        case "MEDIUMINT":
        case "BIGINT":
        case "DECIMAL":
        case "NUMERIC":
        case "FLOAT":
        case "DOUBLE":
        case "REAL":
        case "MONEY":
        case "SMALLMONEY":
        case "DOUBLE PRECISION":
        case "SMALLSERIAL":
        case "SERIAL": 
        case "BIGSERIAL":
        case "INT4":
        case "INT8":
            return true;
        default:
            return false;
    }
}
```

It may be that we need to add a new datatype to that list.

**Comment by s1monj** [comment]
It was the products.units_in_stock which is a smallint - from this test database:
https://github.com/pthom/northwind_psql/blob/master/northwind.sql

I'll look into it some more

**Comment by dand4** [comment]
I setup Northwind and connected QueryTree. From the details you've given I think you've selected the Products.UnitsInStock column and the Suppliers.CompanyName columns, which is what I've done here. The Add Chart button seems to be showing ok for me. Am I doing something wrong?

<img width="260" alt="qt-northwind-addchart" src="https://user-images.githubusercontent.com/20768727/41404436-2257d556-6fbf-11e8-82a2-6e8ca36f3fcd.PNG">

**Comment by s1monj** [comment]
Right thanks - sorry, looks like I have an older version, but I thought I downloaded the latest release
![screenshot from 2018-06-14 12-52-46](https://user-images.githubusercontent.com/16945182/41426542-f6147478-6fd1-11e8-9b09-05c4167c1e0a.png)
