### ISSUE TITLE
export to Excel mangles dates

### ISSUE THREAD

**Issue by mkporwit** [d4software/QueryTree#21]
I have a report generated from MySQL that shows date and time correctly in the web UI. Underlying column is a MySQL DATETIME. When I export the report to Excel (Office 2016 for OS X), the date is mangled. In the web UI, it is "2018-06-29T23:22:59.173", but in excel it shows "1/6/1900  12:00:00 AM". Other dates are similarly mangled.

This happens with the latest published docker image.

<img width="1190" alt="screen shot 2018-07-12 at 6 24 22 pm" src="https://user-images.githubusercontent.com/1071847/42667528-069dea14-8601-11e8-8d40-26af12a1428b.png">
<img width="781" alt="screen shot 2018-07-12 at 6 24 52 pm" src="https://user-images.githubusercontent.com/1071847/42667529-06ba069a-8601-11e8-96e2-f4865928f6de.png">

**Comment by PandelisZ** [comment]
Ah I think i've ran across this before when trying to analyse this date format in CSV. Excel is really not happy with it. I guess the export layer could convert to a more appropriate excel readable format but then again thats not an accurate representation of the data stored in the DB. So swings and roundabouts I guess.

I'll keep you posted in this issue with what is decided on.

**Comment by mkporwit** [comment]
Honestly, I think it would be great if it could just export to a .csv file instead of an .xlsx file.

**Comment by dand4** [comment]
@mkporwit I've pushed a fix for the excel file issue (to both develop and master branches), the 3.0.43-beta release has this fix in it. I'm going to close this issue, but feel free to re-open if you find it's not working, or to log a separate feature request for the .csv export if that's still important to you.
