### ISSUE TITLE
Use dotless instead of npm less

### ISSUE THREAD

**Issue by PandelisZ** [d4software/QueryTree#27]
Might be good to keep everything Csharpy and use dotless as a nuget dependency instead of reaching out to the node world? 

Noticed a few people being caught out by that.

It claims to be compatible with `.NET Standard 2.0 (.NET Core 2.0, Mono 5.4, .NET Framework 4.6.1+)`

https://github.com/dotless/dotless

**Comment by dand4** [comment]
@PandelisZ good idea, I'll look into it.

**Comment by dand4** [comment]
@PandelisZ  this is fixed in develop

**Comment by d4nt** [comment]
This is now fixed in master
