### ISSUE TITLE
[Feature Request] Set home URL

### ISSUE THREAD

**Issue by sidneydemoraes** [d4software/QueryTree#28]
Hello. Would it be possible to add some kind of customization of the home URL likewise Wordpress?
Reason: I am trying to redirect the querytree docker container to `mydomain.com/mydirectory` but all static files point to root (/), which returns 404.

**Comment by ayr-ton** [comment]
The planets are aligned. Just opened #29

**Comment by dand4** [comment]
Duplicate of #29
