### ISSUE TITLE
Summarize does not allow MAX of dates

### ISSUE THREAD

**Issue by sidneydemoraes** [d4software/QueryTree#31]
**Summary**:
I need to create a subselect with MAX(initialDate) GROUP BY id but it was not possible.

**Error**:
All date fields from my table were excluded from the list of columns in the _Summarize_ tool.

**How to Reproduce**:
1. Create a _DataSource_ pointing to your table. _Your table must have at least one DATE column_.
2. Create a _Summarize_ tool from your datasource.
3. In _Calculate the_, choose `Maximum`.
4. In _of column_, look for your `date` field.

**Comment by d4nt** [comment]
I've pushed a fix for this (343268e) to develop, I will merge into master following some testing

**Comment by d4nt** [comment]
This is now fixed.
