### ISSUE TITLE
Advanced Query Builder not returning columns

### ISSUE THREAD

**Issue by tirsoh** [d4software/QueryTree#33]
I am using docker tag 7e0bac0. I am able to query my tables fine with the simple query builder form. But whenever I try to use the advanced query builder and I pick a data table I see the following endpoint returns a http status of 200 but I get the below response:

`api/cache/25ea74e94b1f463e89fbed92d695a88b/dd81a7de-ee10-44ca-a7a4-4ea6a2186643/?startRow=0&rowCount=10`

`{"status":"error","errorText":"42601: syntax error at or near \",\"","columns":[],"columnTypes":[],"rows":[],"rowCount":0,"query":null}`

**Comment by dand4** [comment]
@tirsoh thanks for raising this. I've found the issue and pushed a fix. Please could you update to 4ab96a3 and give it a try?

**Comment by tirsoh** [comment]
Will do. Thanks!
