### ISSUE TITLE
Filter OR

### ISSUE THREAD

**Issue by carlead** [d4software/QueryTree#35]
There is a way to add a filter OR ?

Thanks,

**Comment by dand4** [comment]
Not in the default (or 'simple') query builder. I'd like to introduce a setting that allowed you to toggle between "All filters must be true" and "Any filter can be true". I don't think there's any way to introduce nested clauses (e.g. "X OR (Y AND Z)")  without making the default query builder unusable by it's target audience. 

However, ORs are possible in the Advanced Query Builder using the Append tool. For example: 

<img width="458" alt="screen shot 2018-10-02 at 17 48 37" src="https://user-images.githubusercontent.com/20768727/46363804-f2aca080-c66b-11e8-98e9-7bf970d1e439.png">
