### ISSUE TITLE
Build & Update nuget fails

### ISSUE THREAD

**Issue by papyr** [d4software/QueryTree#38]
updating entity core, design and identity all fail

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "lessc --source-map=Styles/aqb/app.css.map Styles/aqb/app.less Styles/aqb/app.css" exited with code 9009.	

QueryTree	C:\QueryTree\Web\QueryTree.csproj	74	

Error	NU1605	Detected package downgrade: Microsoft.Extensions.Caching.Memory from 2.1.1 to 2.0.0. Reference the package directly from the project to select a different version. 
 QueryTree -> Microsoft.EntityFrameworkCore.Design 2.1.4 -> Microsoft.EntityFrameworkCore.Relational 2.1.4 -> Microsoft.EntityFrameworkCore 2.1.4 -> Microsoft.Extensions.Caching.Memory (>= 2.1.1) 
 QueryTree -> Microsoft.Extensions.Caching.Memory (>= 2.0.0)	QueryTree	C:\QueryTree\Web\QueryTree.csproj	1	
Error	NU1202	Package Microsoft.AspNetCore.All 2.1.5 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.All 2.1.5 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)	QueryTree
	

C:\QueryTree\Web\QueryTree.csproj	1	
Error		Package restore failed. Rolling back package changes for 'QueryTree'.

**Comment by dand4** [comment]
This looks like the issue is, you only have .NET Core 2.1 installed, but QueryTree is referencing .NET Core 2.0 libraries. We should update QueryTree to .NET 2.1.

**Comment by papyr** [comment]
Awesome thanks for the update.

Another question - how do we update querytree nuget code & dlls, can you please share the update command to access the query tree. This would help with adoption as well.

In there query screen is there an option to search text like/contains -- "John*" or Johnson etc.

![image](https://user-images.githubusercontent.com/12733414/47315877-ba1d3880-d613-11e8-8925-6b7899ab85c4.png)

**Comment by dand4** [comment]
> "how do we update querytree nuget code & dlls"
I'm not really sure what this means, what are you trying to achieve?

> In there query screen is there an option to search text like/contains -- "John*" or Johnson etc
No, but you can add more than one filter, and there are options like "Contains", "Starts with" and "Ends with" so you can have combinations of "Starts with" and "Ends with"

> where should I put a break point or how can I catch/watch/copy the pre-constructed and post-constructed query on the backend
Set a breakpoint in the GetSql in [Engine/Query.cs]() or the GetData method in [Web/Managers/DbManager.cs](). You'll see the SQL that is generated by each query that is submitted.

**Comment by papyr** [comment]
It would be nice to update nugets like so 
`>Update-Package Qtree -ProjectName MyProject`

Contains works well, except in the scenario where there are two wild card searches, for e.g. if we wanted all the ID values in [IDjohnDept90shift2, IDJuliaDept90shift3,.. ] `ID*Dept90*` here we want every `ID `with `Dept90`

**Comment by dand4** [comment]
> It would be nice to update nugets like so
>>Update-Package Qtree -ProjectName MyProject

The QueryTree project is built against specific versions of each nuget package. The packages used are defined in the .csproj files. You can't just change the versions of the DLLs that it's using without testing the overall application, but the develop branch is being developed against .NET Core 2.1 and updated versions of various packages. Once develop is ready, we will merge it into master and so the nuget packages used will be updated.

> Lastly is a CSV file possible for a datasource?

No, QueryTree is designed to give users a visual way to generate SQL queries. But you could import the CSV file into a database engine using [sqlizer.io](https://sqlizer.io).

**Comment by dand4** [comment]
@djshres you need to run `npm install less -g`
