### ISSUE TITLE
Improve ```dotnet publish``` step

### ISSUE THREAD

**Issue by TerraVenil** [d4software/QueryTree#41]
Based on [doc](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21) from MS starting from .NET Core 2.0 ```dotnet publish``` command already include restore option. This also can be checked via [publish command](https://github.com/dotnet/cli/blob/1bc19fc6a933de844328095b807453e01f99617d/src/dotnet/commands/dotnet-publish/Program.cs). So you can skip restore step just by specifing ```--no-restore``` option.
Second point related to omitting targeting framework(netcoreapp2.1) option when publish app due to already specified value inside *.csproj file.

**Comment by dand4** [comment]
Fixed by PR42

**Comment by PandelisZ** [comment]
Here you dropped this (ノ^_^)ノ#42
