### ISSUE TITLE
Running from Source issue - exited with code 9009

### ISSUE THREAD

**Issue by solution-man** [d4software/QueryTree#50]
Hi...
i have got an error while Running from Source... 
i installed .net core 2.0 and 2.1 and 2.2 separately but below error occurred.

...\Web>dotnet run
error MSB3073: The command "lessc --source-map=Styles/aqb/app.css.map Styles/aqb/app.less Styles/aqb/app.css" exited with code 9009

**Comment by dand4** [comment]
@solution-man You need to run "npm install". Check the README. Alternatively, switch to the develop branch where that dependency has been removed.

**Comment by solution-man** [comment]
Thanks a lot for your response.
how can i switch to the develop branch?

**Comment by dand4** [comment]
@solution-man check the git documentation https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

**Comment by solution-man** [comment]
ok, i have done "npm install" but the error still exist. 
1- which version of .net core i have to use?
2- "npm install less -g" is the only one install i should do?
