### ISSUE TITLE
Editing an existing report

### ISSUE THREAD

**Issue by Dunkiep** [d4software/QueryTree#51]
Create a new report with no filters connecting to SQL server.

View report works fine.

Edit report, click "Filter your data" then "Add Filter"
![filter value missing](https://user-images.githubusercontent.com/48279038/53871942-1433fe80-3ff5-11e9-8f06-6943b55fa58f.PNG)
The "Value" box is missing making adding new filters impossible.

**Comment by FileJunkie** [comment]
The bug is on `Web/Views/Simple/Edit.cshtml` file, line 117. Change `name` to `type` there to make it the same as `Create.cshtml`.

**Comment by dand4** [comment]
Awesome, thanks @FileJunkie
