### ISSUE TITLE
Long requests

### ISSUE THREAD

**Issue by Lusocoder** [d4software/QueryTree#52]
Been playing with QueryTree and found a bit of a problem.

When running queries on tables with a lot of fields we may get an error from the server:
"The request filtering module is configured to deny a request where the query string is too long."

Basically the problem is that all fields, are being passed on the query string and with a few other properties like searchable, regex, etc.

This makes the request too long.

When exporting to Excel there is no problem, because it only makes a http://localhost:54181/api/queries/1/export 

instead of this request bellow:

http://localhost:54181/api/queries/1/?draw=1&columns[0][data]=0&columns[0][name]=&columns[0][searchable]=true&columns[0][orderable]=false&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=1&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=2&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=3&columns[3][name]=&columns[3][searchable]=true&columns[3][orderable]=false&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=4&columns[4][name]=&columns[4][searchable]=true&columns[4][orderable]=false&columns[4][search][value]=&columns[4][search][regex]=false&columns[5][data]=5&columns[5][name]=&columns[5][searchable]=true&columns[5][orderable]=false&columns[5][search][value]=&columns[5][search][regex]=false&columns[6][data]=6&columns[6][name]=&columns[6][searchable]=true&columns[6][orderable]=false&columns[6][search][value]=&columns[6][search][regex]=false&columns[7][data]=7&columns[7][name]=&columns[7][searchable]=true&columns[7][orderable]=false&columns[7][search][value]=&columns[7][search][regex]=false&columns[8][data]=8&columns[8][name]=&columns[8][searchable]=true&columns[8][orderable]=false&columns[8][search][value]=&columns[8][search][regex]=false&columns[9][data]=9&columns[9][name]=&columns[9][searchable]=true&columns[9][orderable]=false&columns[9][search][value]=&columns[9][search][regex]=false&columns[10][data]=10&columns[10][name]=&columns[10][searchable]=true&columns[10][orderable]=false&columns[10][search][value]=&columns[10][search][regex]=false&columns[11][data]=11&columns[11][name]=&columns[11][searchable]=true&columns[11][orderable]=false&columns[11][search][value]=&columns[11][search][regex]=false&columns[12][data]=12&columns[12][name]=&columns[12][searchable]=true&columns[12][orderable]=false&columns[12][search][value]=&columns[12][search][regex]=false&columns[13][data]=13&columns[13][name]=&columns[13][searchable]=true&columns[13][orderable]=false&columns[13][search][value]=&columns[13][search][regex]=false&columns[14][data]=14&columns[14][name]=&columns[14][searchable]=true&columns[14][orderable]=false&columns[14][search][value]=&columns[14][search][regex]=false&columns[15][data]=15&columns[15][name]=&columns[15][searchable]=true&columns[15][orderable]=false&columns[15][search][value]=&columns[15][search][regex]=false&columns[16][data]=16&columns[16][name]=&columns[16][searchable]=true&columns[16][orderable]=false&columns[16][search][value]=&columns[16][search][regex]=false&columns[17][data]=17&columns[17][name]=&columns[17][searchable]=true&columns[17][orderable]=false&columns[17][search][value]=&columns[17][search][regex]=false&columns[18][data]=18&columns[18][name]=&columns[18][searchable]=true&columns[18][orderable]=false&columns[18][search][value]=&columns[18][search][regex]=false&columns[19][data]=19&columns[19][name]=&columns[19][searchable]=true&columns[19][orderable]=false&columns[19][search][value]=&columns[19][search][regex]=false&columns[20][data]=20&columns[20][name]=&columns[20][searchable]=true&columns[20][orderable]=false&columns[20][search][value]=&columns[20][search][regex]=false&columns[21][data]=21&columns[21][name]=&columns[21][searchable]=true&columns[21][orderable]=false&columns[21][search][value]=&columns[21][search][regex]=false&columns[22][data]=22&columns[22][name]=&columns[22][searchable]=true&columns[22][orderable]=false&columns[22][search][value]=&columns[22][search][regex]=false&columns[23][data]=23&columns[23][name]=&columns[23][searchable]=true&columns[23][orderable]=false&columns[23][search][value]=&columns[23][search][regex]=false&columns[24][data]=24&columns[24][name]=&columns[24][searchable]=true&columns[24][orderable]=false&columns[24][search][value]=&columns[24][search][regex]=false&columns[25][data]=25&columns[25][name]=&columns[25][searchable]=true&columns[25][orderable]=false&columns[25][search][value]=&columns[25][search][regex]=false&columns[26][data]=26&columns[26][name]=&columns[26][searchable]=true&columns[26][orderable]=false&columns[26][search][value]=&columns[26][search][regex]=false&columns[27][data]=27&columns[27][name]=&columns[27][searchable]=true&columns[27][orderable]=false&columns[27][search][value]=&columns[27][search][regex]=false&columns[28][data]=28&columns[28][name]=&columns[28][searchable]=true&columns[28][orderable]=false&columns[28][search][value]=&columns[28][search][regex]=false&columns[29][data]=29&columns[29][name]=&columns[29][searchable]=true&columns[29][orderable]=false&columns[29][search][value]=&columns[29][search][regex]=false&columns[30][data]=30&columns[30][name]=&columns[30][searchable]=true&columns[30][orderable]=false&columns[30][search][value]=&columns[30][search][regex]=false&columns[31][data]=31&columns[31][name]=&columns[31][searchable]=true&columns[31][orderable]=false&columns[31][search][value]=&columns[31][search][regex]=false&columns[32][data]=32&columns[32][name]=&columns[32][searchable]=true&columns[32][orderable]=false&columns[32][search][value]=&columns[32][search][regex]=false&columns[33][data]=33&columns[33][name]=&columns[33][searchable]=true&columns[33][orderable]=false&columns[33][search][value]=&columns[33][search][regex]=false&columns[34][data]=34&columns[34][name]=&columns[34][searchable]=true&columns[34][orderable]=false&columns[34][search][value]=&columns[34][search][regex]=false&columns[35][data]=35&columns[35][name]=&columns[35][searchable]=true&columns[35][orderable]=false&columns[35][search][value]=&columns[35][search][regex]=false&columns[36][data]=36&columns[36][name]=&columns[36][searchable]=true&columns[36][orderable]=false&columns[36][search][value]=&columns[36][search][regex]=false&columns[37][data]=37&columns[37][name]=&columns[37][searchable]=true&columns[37][orderable]=false&columns[37][search][value]=&columns[37][search][regex]=false&columns[38][data]=38&columns[38][name]=&columns[38][searchable]=true&columns[38][orderable]=false&columns[38][search][value]=&columns[38][search][regex]=false&columns[39][data]=39&columns[39][name]=&columns[39][searchable]=true&columns[39][orderable]=false&columns[39][search][value]=&columns[39][search][regex]=false&columns[40][data]=40&columns[40][name]=&columns[40][searchable]=true&columns[40][orderable]=false&columns[40][search][value]=&columns[40][search][regex]=false&columns[41][data]=41&columns[41][name]=&columns[41][searchable]=true&columns[41][orderable]=false&columns[41][search][value]=&columns[41][search][regex]=false&columns[42][data]=42&columns[42][name]=&columns[42][searchable]=true&columns[42][orderable]=false&columns[42][search][value]=&columns[42][search][regex]=false&columns[43][data]=43&columns[43][name]=&columns[43][searchable]=true&columns[43][orderable]=false&columns[43][search][value]=&columns[43][search][regex]=false&columns[44][data]=44&columns[44][name]=&columns[44][searchable]=true&columns[44][orderable]=false&columns[44][search][value]=&columns[44][search][regex]=false&columns[45][data]=45&columns[45][name]=&columns[45][searchable]=true&columns[45][orderable]=false&columns[45][search][value]=&columns[45][search][regex]=false&columns[46][data]=46&columns[46][name]=&columns[46][searchable]=true&columns[46][orderable]=false&columns[46][search][value]=&columns[46][search][regex]=false&columns[47][data]=47&columns[47][name]=&columns[47][searchable]=true&columns[47][orderable]=false&columns[47][search][value]=&columns[47][search][regex]=false&columns[48][data]=48&columns[48][name]=&columns[48][searchable]=true&columns[48][orderable]=false&columns[48][search][value]=&columns[48][search][regex]=false&columns[49][data]=49&columns[49][name]=&columns[49][searchable]=true&columns[49][orderable]=false&columns[49][search][value]=&columns[49][search][regex]=false&columns[50][data]=50&columns[50][name]=&columns[50][searchable]=true&columns[50][orderable]=false&columns[50][search][value]=&columns[50][search][regex]=false&columns[51][data]=51&columns[51][name]=&columns[51][searchable]=true&columns[51][orderable]=false&columns[51][search][value]=&columns[51][search][regex]=false&columns[52][data]=52&columns[52][name]=&columns[52][searchable]=true&columns[52][orderable]=false&columns[52][search][value]=&columns[52][search][regex]=false&columns[53][data]=53&columns[53][name]=&columns[53][searchable]=true&columns[53][orderable]=false&columns[53][search][value]=&columns[53][search][regex]=false&columns[54][data]=54&columns[54][name]=&columns[54][searchable]=true&columns[54][orderable]=false&columns[54][search][value]=&columns[54][search][regex]=false&columns[55][data]=55&columns[55][name]=&columns[55][searchable]=true&columns[55][orderable]=false&columns[55][search][value]=&columns[55][search][regex]=false&columns[56][data]=56&columns[56][name]=&columns[56][searchable]=true&columns[56][orderable]=false&columns[56][search][value]=&columns[56][search][regex]=false&columns[57][data]=57&columns[57][name]=&columns[57][searchable]=true&columns[57][orderable]=false&columns[57][search][value]=&columns[57][search][regex]=false&columns[58][data]=58&columns[58][name]=&columns[58][searchable]=true&columns[58][orderable]=false&columns[58][search][value]=&columns[58][search][regex]=false&columns[59][data]=59&columns[59][name]=&columns[59][searchable]=true&columns[59][orderable]=false&columns[59][search][value]=&columns[59][search][regex]=false&columns[60][data]=60&columns[60][name]=&columns[60][searchable]=true&columns[60][orderable]=false&columns[60][search][value]=&columns[60][search][regex]=false&columns[61][data]=61&columns[61][name]=&columns[61][searchable]=true&columns[61][orderable]=false&columns[61][search][value]=&columns[61][search][regex]=false&start=0&length=10&search[value]=&search[regex]=false&_=1552047877908

**Comment by dand4** [comment]
Thanks @Lusocoder, I've noticed this too. Partly this is because we're using the https://datatables.net/ plugin. I'm open to alternative suggestions on this but for now I've changed the HTTP request to a POST to /api/getquerydata/{queryId}/ in the develop branch. It's not ideal as the request is only fetching data and should really be represented by a GET, but it solves the URL length issues.

**Comment by Lusocoder** [comment]
> 
> 
> Thanks @Lusocoder, I've noticed this too. Partly this is because we're using the https://datatables.net/ plugin. I'm open to alternative suggestions on this but for now I've changed the HTTP request to a POST to /api/getquerydata/{queryId}/ in the develop branch. It's not ideal as the request is only fetching data and should really be represented by a GET, but it solves the URL length issues.

Thanks :) Will check it out.

About alternatives, I don't have one at the moment. Perhaps addressing this issue with Datatables guys and see what they propose as a solution? There seems to be a lot of redundant stuff on the query.
