### ISSUE TITLE
Query across multiple databases 

### ISSUE THREAD

**Issue by blackchineykh** [d4software/QueryTree#54]
Hi,

I was reviewing the documentation but couldn't identify if this tool is able to query across multiple databases on different servers for a single report. 

In my case the databases are mysql and I didn't want to go the federated route so if this is possible then this tool would be perfect!

**Comment by dand4** [comment]
@blackchineykh I'm afraid not, each report in QueryTree connects to a single database.

**Comment by blackchineykh** [comment]
Thank you
