### ISSUE TITLE
Unable to build from source with .Net Core 2.2.105 SDK

### ISSUE THREAD

**Issue by Autoflow** [d4software/QueryTree#56]
Errror given is: 

C:\QueryTree Server\Web\QueryTree.csproj(73,5): error MSB3073: Der Befehl "lessc --source-map=Styles/aqb/app.css.map Styles/aqb/app.less Styles/aqb/app.css" wurde mit dem Code 9009 beendet.

Any suggestions?

**Comment by dand4** [comment]
You need to install "less", you can use the following command `npm install less -g`. See the README for more information.
