### ISSUE TITLE
Update CI and docker to new upstream .net core images

### ISSUE THREAD

**Issue by PandelisZ** [d4software/QueryTree#65]
Looks like Microsoft has restructured their docker hub images of dotnet.

from CI
```
Build-agent version 1.0.11354-0d3b5199 (2019-05-16T02:00:37+0000)
Docker Engine Version: 18.09.1
Kernel Version: Linux 8c8a2725d557 4.15.0-1035-aws #37-Ubuntu SMP Mon Mar 18 16:15:14 UTC 2019 x86_64 Linux
Starting container microsoft/aspnetcore-build:2.2-stretch
  image cache not found on this host, downloading microsoft/aspnetcore-build:2.2-stretch

Error response from daemon: manifest for microsoft/aspnetcore-build:2.2-stretch not found

```

from microsoft/aspnetcore-build:  **Latest images for 2.1 and newer are now available on dotnet/core. See this link for more details about migrating to 2.1.**

i think the equivalent would be : `microsoft/aspnetcore-build:2.2` -> `mcr.microsoft.com/dotnet/core/sdk:2.2`

and `microsoft/aspnetcore:2.0-stretch` -> `mcr.microsoft.com/dotnet/core/aspnet:2.2`

Where this would need changing:

- The dockerfile: https://github.com/d4software/QueryTree/blob/master/Dockerfile
- The circle ci config: https://github.com/d4software/QueryTree/blob/master/.circleci/config.yml

**Comment by dand4** [comment]
@PandelisZ I think I fixed this in 1fc1469 (in develop). But that was a part of a broader change where I removed our dependence on NPM. We could pick our those lines into master if necessary though.

**Comment by PandelisZ** [comment]
Hmmmm that was from CI on develop failing though so don't think that quite did it.

https://circleci.com/gh/d4software/QueryTree/499?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

<img width="720" alt="Screenshot 2019-05-17 at 22 23 47" src="https://user-images.githubusercontent.com/8436717/57956929-8b89e680-78f2-11e9-8ec8-88e274d3c3c8.png">

**Comment by PandelisZ** [comment]
AH! Its actually the CI ones are missing. I'll match them up to be the same as the docker file. Thanks for the info @dand4
