### ISSUE TITLE
Where is Chart option in  d4software/querytree:latest  image?

### ISSUE THREAD

**Issue by maulik-modi** [d4software/QueryTree#71]
I have downloaded Docker image of query tree (d4software/querytree:latest), setup connection to Postgres database. It seems "Chart" option is not available, how do I activate Chart option? 

Refer attached image.
![image](https://user-images.githubusercontent.com/34910430/59497216-9e231b80-8eb0-11e9-9822-d61c03859636.png)

**Comment by dand4** [comment]
@maulik-modi The chart option appears when there are numeric columns in the table (and there are 2 or more columns, which is true in this case). Otherwise the Chart cannot display anything.
