### ISSUE TITLE
No Tables Found

### ISSUE THREAD

**Issue by AliviQuery** [d4software/QueryTree#72]
Hi, 

I'm running QueryTree with a Docker. I can connect to all databases on the server and create reports with the exception of one database. When I create a new report it just shows "No tables found". I've confirmed the permissions and I can't seem to find anything different with this one database.

![Capture](https://user-images.githubusercontent.com/51954685/59678288-fea8a600-9199-11e9-8866-a3fd8a2cbd39.PNG)

**Comment by dand4** [comment]
@AliviQuery it looks like there's something about the structure of that database that's tripping it up. Maybe there's a column type that it doesn't recognise. The server process should be outputting an error to the console, perhaps you could find that and post it here?

Alternatively,  take a look at the [GetDbModel method in DbManager](https://github.com/d4software/QueryTree/blob/021242272b3875163dc18981f43d9e1359676a2e/Web/Managers/DbManager.cs#L139). Depending on the of database this is, it runs a query to determine what tables and columns are there. What does that return for this database?

**Comment by AliviQuery** [comment]
@dand4 i'm attaching the output of the GetDbModel method in DbManager. We are using Microsoft SQL Server 2016. I attached a screenshot of the error message from the Console. It just gives a 404 error. 
[QueryTreeOutpout.xlsx](https://github.com/d4software/QueryTree/files/3306967/QueryTreeOutpout.xlsx)

**Comment by AliviQuery** [comment]
@dand4 is there known issues with certain column types? Maybe I can limit scope of what I'm looking for. I created a duplicate instance of the database in question and removed all objects and left only tables. I still got the error. I had to drop close to 80% of the tables before the error disappeared. Problem is I don't know which table is the problem. Adding them back one by one and testing each time is going to take a considerable amount of time.

**Comment by AliviQuery** [comment]
@d4nt finally resolved the issue. On the function SetDbForeignKeys of the class DbManager in the line 409 it is not evaluated if the object "dbTable" is null before using it to assign the value of column.Parent. Solved  by evaluating if dbTable is different to null, then if true, assign the value of column.Parent.

**Comment by jahmia** [comment]
@AliviQuery how do you do exactly, i'm not a .NET developer ? I'm facing the same problem using postgresql, **No tables found**
`if (dbTable != null)           
{
       column.Parent = dbTable.Columns[0] as Models.DbColumn;
}`

**Comment by d4nt** [comment]
I believe this bug was fixed in the develop branch by a8f8fef, which I've cherry picked into master now.
