### ISSUE TITLE
The Graphing only graphs the current page of results

### ISSUE THREAD

**Issue by jkbaumohl** [d4software/QueryTree#80]
The Graphing only graphs the current page (10 rows) of results.
The graphing should graph all the rows.
Most tables have more than 10 rows, as it stands now this feature is near useless.

**Comment by d4nt** [comment]
@jkbaumohl thanks for this. I've pushed a fix to develop. 

Note: this is an issue when editing the query but not when viewing a saved report.

**Comment by d4nt** [comment]
This is now fixed
