### ISSUE TITLE
Publish Reports

### ISSUE THREAD

**Issue by daboti** [d4software/QueryTree#82]
Recently I have installed the querytreeapp (a great tool by the way). 
After successful setup a mysql database, I create my first report (pie chart), but the problem is I cannot publish (as embedded content on iframe) since the button doesn't exist like in your demo video.
Can you help me, please? Or in the code what i have to do, to publish a report as embedded?
Can you give me a example?
Best Regards,
Fernando Oliveira

**Comment by d4nt** [comment]
Hi @daboti, what video are you referring to? I think that might have been an old feature from a long time ago when QueryTree was a hosted SaaS service.

**Comment by daboti** [comment]
Hi, @d4nt, 
the video is this one: https://www.youtube.com/watch?v=UWp4_TNu1yU
I'm looking for this feature (publish), can you give me a tip, how can I change the code (what files)?

Thanks

**Comment by d4nt** [comment]
@daboti yeah, that's a very old video and that's not a feature that QueryTree has any more.  I will take that video down to avoid confusion for others.

If you were going to do this yourself you've need to:

- Add a PublishedId to the Query entity (and therefore the Queries) table.
- Add a button somewhere labelled "Publish" that generates a PublishedId for whichever query you are on when you press the button. The PublishedId should be a long random token, something like 128 bytes, generated using RNGCryptoServiceProvider.
- Add a new controller, PublishedController, with an action that handles requests to /published/{publishedQueryId}/
- Allow anonymous access to that route.
- Create a view for this route that is based on [/Web/Views/Queries/Details.cshtml](https://github.com/d4software/QueryTree/blob/master/Web/Views/Queries/Details.cshtml) but that doesn't have the the "Edit" button, a header menu, or any of the scheduling features. That view will load the data from the API using the {publishedQueryId}

Hope that helps, if you get it done it'd be interesting to see a Pull Request for this!
