### ISSUE TITLE
Unable to filter based on PostgreSQL varchar fields

### ISSUE THREAD

**Issue by synyker** [d4software/QueryTree#84]
When adding a filter either from the basic or advanced query builder, I am unable to create filters for `varchar` type fields. The comparison type dropdown is just empty. It works fine with `text` type fields, though.

I am using the latest Docker version of QueryTree, also tried with a couple of older builds. The database is running PostgreSQL 9.6.

**Comment by d4nt** [comment]
@synyker Thanks for raised this, I've invested and pushed a fix (cb9bb21).
