### ISSUE TITLE
Can multiple tables be selected and linked?

### ISSUE THREAD

**Issue by bmcgonag** [d4software/QueryTree#87]
I like this project, it's very nice.  I am using it and wondering if multiple tables could be selected and linked.  This would be a great tool for non SQL gurus, but if they have to know how to write views in order to link tables, it's not super helpful. 

I'm happy to contribute if I can in testing or otherwise.

Is there a roadmap, feature backlog somewhere that can be viewed?

**Comment by d4nt** [comment]
There’s no specific roadmap, but Issues that I think would be useful for the target audience get tagged as “pinned” and eventually I get round to them. So checkout the issues list.

**Comment by d4nt** [comment]
Closing this issue a the question has been answered.
