### ISSUE TITLE
Question: CJIS / FIPS-140-2?

### ISSUE THREAD

**Issue by bmcgonag** [d4software/QueryTree#88]
Is there a way to use WireGuard in a FIPS 140-2 compliant way? Are the cryptographic modules used FIPS 140-2 certified?

The feature that WireGuard “reconnects” between network jumps is an amazing thing that would help meet CJI requirements for public safety mobile users trying to get timely information in life critical situations. 

Thanks for the project! Loving it no matter what.

**Comment by d4nt** [comment]
I see no reason why you couldn't run QueryTree connecting to a database over a WireGuard network.
