### ISSUE TITLE
Add SmtpHostPort as a confurable property

### ISSUE THREAD

**Issue by PandelisZ** [d4software/QueryTree#9]
https://github.com/d4software/QueryTree/blob/c54fc65e3d7693804d6f712778a247cee909a945/Web/Services/MessageServices.cs#L34

Google apps for example prefers 465 for SSL, port 587 flags up as insecure and doesn't allow you to send mail

Update https://github.com/d4software/QueryTree/blob/master/docs/mail.md with new field to get gmail working

**Comment by dand4** [comment]
@PandelisZ I've fixed this in develop.

**Comment by PandelisZ** [comment]
Looks like gmails ssl port doesnt connect at all and the tls port still complains that the method is not secure enough.

This needs to be looked into a bit more if we want gmail support.

Had to use mailgun smtp login for testing

**Comment by dand4** [comment]
@PandelisZ I've added a UseSSL setting, and updated the docs at https://github.com/d4software/QueryTree/blob/develop/docs/mail.md. I've tested with gmail on a9038af527754f98d351dba9c8f148bd083fbf01 and all seems well.
