### ISSUE TITLE
MySQL Failed to connect

### ISSUE THREAD

**Issue by markus07** [d4software/QueryTree#92]
When I configured connection to DB and trying to test it I got error "Failed to connect"

I can see in mysql logs that connection was successful also I can see via tcpdump that traffic comes and goes.

Is there any limitation for MySQL DB version? I got old one 5.1.73

**Comment by d4nt** [comment]
Thanks @markus07. There’s no known minimum version of MySQL, but I suspect this might be the problem.

Are you about to debug the source? If you are could you look at DbManager.TryUseDbConnection(). Is it catching a `MySqlException`?

**Comment by markus07** [comment]
I use docker and I am not sure how to do that, could you please tell me how to do it?

**Comment by jczanfona** [comment]
Same result with MySQL 5.5.24
(with root without pwd in case it is a problem)
