### ISSUE TITLE
Fail to run

### ISSUE THREAD

**Issue by jczanfona** [d4software/QueryTree#93]
I'm having an error with command **dotnet run** in _Web_ folder:
> .nuget\packages\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(131,5): error : rzc generate exited with code -2147450730. [C:\Apps\QueryTree\Web\QueryTree.csproj]

and cannot compile...

This is my **dotnet --info**:
SDK de .NET Core (reflejando cualquier global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by PandelisZ** [comment]
You're going to need to install and run with .NET 2.2 

https://github.com/d4software/QueryTree/issues/86

**Comment by jczanfona** [comment]
For that version the support ended on 2019-12-23 but I will try to see. Thank you!

**Comment by PandelisZ** [comment]
Thanks for reporting that @jczanfona I've created a new issue to push for fixing the compile issues with .NET Core 3
