### ISSUE TITLE
Support for .NET 3+

### ISSUE THREAD

**Issue by PandelisZ** [d4software/QueryTree#94]
2.2 is no longer supported by microsoft.
![Screenshot 2020-01-13 at 11 08 57](https://user-images.githubusercontent.com/8436717/72247467-3a530380-35f5-11ea-9767-515d3efc7b7e.png)

https://dotnet.microsoft.com/download/dotnet-core/2.2

Two related issues to people not being able to compile:
https://github.com/d4software/QueryTree/issues/93
https://github.com/d4software/QueryTree/issues/86

**Comment by raynebair** [comment]
Any idea on when this update might be available? Our servers run 3.1 and agency policies restrict me from installing 2.2 because of the end-of-life.

**Comment by PandelisZ** [comment]
Feel free to have a go at the upgrade. Its not anything we're planning to do any time soon though.

Would probably mostly involve upgrading packages and syntax for new packages and apis here and there.

**Comment by mdduarte1970** [comment]
Hello, there are several components that are already obsolete, when will they be able to update it. Since the product is very good, but little by little it is becoming obsolete.

**Comment by kijoyin** [comment]
@PandelisZ  - I was looking into using it for something and ended up upgrading it to dotnet6 (for most part anyway). Some NuGet packages can be updated but for now , this is all I am going to get to. What is the best way to submit a pull request for this ?

**Comment by d4nt** [comment]
Closing this, as we're now on dotnet 6
