### ISSUE TITLE
Export Node?

### ISSUE THREAD

**Issue by mattosaurus** [d4software/QueryTree#95]
Hi, I really like this project, good work :)

Is it possible to add in an export node in the advanced edit so the resulting records could be output (to a CSV maybe)?

If this isn't something you're currently working on would you have any suggestions of where to start for me to try and add this functionality myself?

**Comment by d4nt** [comment]
Hi @mattosaurus, the ability to export results is a part of the UI:

In the simple query builder:
![Screenshot 2020-02-17 at 20 27 41](https://user-images.githubusercontent.com/20768727/74684610-44ec5400-51c4-11ea-9e30-0922d5882682.png)

and in the advanced query builder:
![Screenshot 2020-02-17 at 20 28 37](https://user-images.githubusercontent.com/20768727/74684648-57668d80-51c4-11ea-8e32-247a29a655c7.png)

In both cases the data is saved as an Excel (.xlsx) file.
