### ISSUE TITLE
How to change listeing IP address

### ISSUE THREAD

**Issue by mateoayat** [d4software/QueryTree#96]
Hi:

I am mounting QueryTree on a Linux server, but it only listens to localhost. How can I change the IP the program listens to? Or how should I handle mounting the program on a server?

**Comment by PandelisZ** [comment]
You should have a couple of options depending on how you're running the app.

Dotnet run:
`dotnet run --urls="http://localhost:5001"`

Environment variable
`ASPNETCORE_URLS=http://+:5001`


https://stackoverflow.com/questions/37365277/how-to-specify-the-port-an-asp-net-core-application-is-hosted-on

**Comment by mateoayat** [comment]
Thank you very much!
