### ISSUE TITLE
Creating reports for the last N days

### ISSUE THREAD

**Issue by mateoayat** [d4software/QueryTree#98]
While creating reports, one may filter the data based on the dates associated with the rows. There are many helpful options to filter before a certain day, after a certain day, or on set time intervals (last day, last 45 days, last 90 days). Is it possible to filter by a last set number of days? For example, to set the report to retrieve the data from the last 365 days to create a yearly report. Even in the advanced report builder, there is no option to set current date minus an arbitrary amount of time.

**Comment by d4nt** [comment]
@mateoayat That's a good idea. I've pushed an initial implementation of that feature on the develop branch. It needs a bit more testing but you're welcome to take a look at let me know if you find any issues.

**Comment by mateoayat** [comment]
So far it works great! Thanks! I'll keep the thread open for any eventualities
